exit function upgrade

diff --git a/bashShelter b/bashShelter
--- a/bashShelter
+++ b/bashShelter
@@ -1,5 +1,19 @@
 #! /bin/bash 
-config="$HOME/.config/shelter/"
+# config="$HOME/.config/shelter/"
+# encryptedFile="$HOME/.config/shelter_p"
+encryptedFileName="shelter.tar.gpg"
+encryptedFileLocation="/media/veracrypt1"
+encryptedFile="$encryptedFileLocation/$encryptedFileName"
+
+# where to temporarily unpack?
+configDir="$HOME.config"
+# tmp file name
+configFileName="shelter"
+# name of unpacked file
+config="$configDir/$configFileName"
+
+trap appExit EXIT
+trap appExit ERR
 
 
 function helpMsg(){
@@ -12,45 +26,130 @@ function helpMsg(){
 	echo "		shelter - shelterName"
 	echo "		f - filename"
 	echo "		pass - password to encrypt"
-
-
 }
+ 
+function appExit {
+	tree2=`ls -R $config`
+
+	if [[ $tree1 != $tree2 ]]; then
+		res=""
+
+		read  -e -p "want to save? y/N:  " res
+
+		if [[ $res == "N" || $res == "n" ]]; then
+			echo "aborting"
+		else
+			{
+				cp $encryptedFile "$encryptedFileLocation/.$encryptedFileName""_0"
+				# err=`gpgtar -C $configDir -c --output $encryptedFile $configFileName  > /dev/null` 
+				echo "gpgtar -C $configDir -c --output $encryptedFile $configFileName"
+			
+				for (( i = 1; i <= 6; i++ )); do
+					if [[ $i == 6 ]]; then
+						setBackup
+						break
+					fi	
+					
+					echo "$i/5 attempt"
+					if [[ $i == 5 ]]; then
+						echo "last attempt!!"
+					fi
+					
+					#try
+					{
+						err=`gpgtar -C $configDir -c --output $encryptedFile $configFileName  2>&1`
+						if ! [[ $err ]];then
+							break;
+						fi
+					#except
+					}||{
+						echo "failed"
+						
+
+					}
+				done
+				echo "gpgtar succeed"
+				rm	"$encryptedFileLocation/.$encryptedFileName""_0"
+
+				
+			}||{
+				echo "password input failed, try again."
+				echo "saving error"
+			}
+
+		fi
+
+
+	fi
+	rm -r $config
+	exit 0
+}
+
+function setBackup {
+	echo setBackup
+	mv "$encryptedFileLocation/.$encryptedFileName""_0" $encryptedFile
+}
+
+# function appExitBACK {
+# 	tree2=`ls -R $config`
+
+# 	if [[ $tree1 != $tree2 ]]; then
+# 		res=""
+
+# 		read  -e -p "want to save? y/N:  " res
+
+# 		if [[ $res == "N" || $res == "n" ]]; then
+# 			echo "aborting"
+# 			rm -r $config
+
+# 		else
+# 			{
+# 				while [[ 1 ]]; do
+# 				cp $encryptedFile "$encryptedFileLocation/.$encryptedFileName""_0"
+# 				# err=`gpgtar -C $configDir -c --output $encryptedFile $configFileName  > /dev/null` 
+				
+# 				if [[ `gpgtar -C $configDir -c --output $encryptedFile $configFileName  ` ]]; then
+# 					exit "gpgtar succeed"
+# 				else
+# 					echo failed
+# 					echo $err
+# 					# mv "$encryptedFileLocation/.$encryptedFileName""_0" $encryptedFile
+					
+# 				fi
+# 				echo "password input failed, try again."
+# 				done				
+# 			}||{
+# 				echo "saving error"
+# 			}
+# 			rm -r $config
+# 		fi
+# 	else
+# 			rm -r $config
+# 	fi
+
+# 	exit 0
+# }
+
 
 
 function clipboard(){
-	echo $passwd | xclip -selection clipboard
-	echo "copied"
-}
 
-
-function read_gpg(){
-	
-	passwd=`gpg -d $1 2>/dev/null`
+	passwd=`cat $1`
 
 	if [[ $passwd == "" ]]; then
-		echo "not gpg"
+		echo "cannot read content of the file"
 		
 	else
-		clipboard
-
+		echo $passwd | xclip -selection clipboard
+		echo "copied"
 	fi
 	passwd=""
 
 }
-function create_gpg(){
-
-	echo ${array[i+1]} > $config$shelter/${array[i]}
-	gpg --output $config$shelter/${array[i]}.tmp --symmetric $config$shelter/${array[i]}
-	rm $config$shelter/${array[i]}
-	mv $config$shelter/${array[i]}.tmp  $config$shelter/${array[i]}
-		
-}
-
 
 function printout(){
 	ls $config/$arg1/* 1>/dev/null 2>/dev/null || gpg=1
 		
-
 		if [[ $gpg == 0 ]] || [[ $show == 1 ]];then
 			
 			for elem in $tmplist
@@ -59,7 +158,8 @@ function printout(){
 			done	
 
 			else
-				read_gpg $tmplist
+				# read_gpg $tmplist
+				clipboard $tmplist
 				gpg=0;
 			fi
 }
@@ -81,6 +181,7 @@ function list_shelters(){
 
 	if [[ $1 ]];then
 	{
+	#try
 			cwd=${arg1}
 
 			if [[ ("${cwd: -1}" == "/") ]]; then
@@ -90,16 +191,19 @@ function list_shelters(){
 			fi
 
 			tmplist=`ls -w 1 $config/$arg1 2>/dev/null`
+	}||{
+	# exccept
+		{
+		#try
+			tmplist=`ls -w 1 $config/$arg1* 2>/dev/null`
 		}||{
-			{
-				tmplist=`ls -w 1 $config/$arg1* 2>/dev/null`
-			}||{
-				tmplist=`ls -w 1 $config 2>/dev/null`
-				echo '<---- '$arg1' not found ---->'
-				show=1
-				cwd=""
-			}
+		#except
+			tmplist=`ls -w 1 $config 2>/dev/null`
+			echo '<---- '$arg1' not found ---->'
+			show=1
+			cwd=""
 		}
+	}
 
 		if [[ $tmplist == "" ]]; then
 			echo '<---- '$arg1' is empty ---->'
@@ -118,13 +222,12 @@ function list_shelters(){
 }
 
 function createShelter(){
-
 	array=("$@")
 	array=("${array[@]:1}") 
 
 	lol=$(list_shelters $array)
 	if [[ $lol == *"not found"* ]]; then
-		mkdir $config$array
+		mkdir $config/$array
 	else
 		echo '<---- '$array' already exists ---->' 
 	fi
@@ -144,11 +247,9 @@ function addPasswords(){
 	for i in ${!array[@]}
 		do
 			if !(( i%2  )); then
-				create_gpg	
+				echo ${array[i+1]} > $config/$shelter/${array[i]}
 			fi
-			
 		done
-
 	unset $array
 }
 function delete(){
@@ -165,80 +266,79 @@ function delete(){
 		done
 }
 
-function show_keys(){
-	ls $config/.config/keys
-}
+if [[ `gpgtar -C $configDir --decrypt $encryptedFile 2>&1 2>/dev/null` ]]; then
+	echo success
+else
+	echo error
 
-history=()
-	cwd=""
+fi
+tree1=`ls -R $config`
 
-	if [[ ! -e $config ]];then
-		mkdir -p ~/.shelter
-	fi
+cwd=""
 
-	list=`ls -w 1 $config 2>/dev/null` 
+if [[ ! -e $config ]];then
+	mkdir -p ~/.shelter
+fi
 
-	if [[ $2 != ""  ]]; then
-		list_shelters $1/$2
-		exit 0
+list=`ls -w 1 $config 2>/dev/null` 
 
-	elif [[ $1 != "" ]]; then
+if [[ $2 != ""  ]]; then
+	list_shelters $1/$2
+	exit 0
 
-		case $1 in
-			*/*)
-				split $1
+elif [[ $1 != "" ]]; then
+
+	case $1 in
+		*/*)
+			# split $1
+			printout $1
+			;;
+		-h|--help)
+			helpMsg
+			;;
+		*)
+			list_shelters $1
+			;;
+
+	esac
+	exit 0
+
+else
+	while [[ 1 ]]; do
+
+		read  -e -p "shelter>" -i "$cwd" com
+
+		if [[ $com == "" ]];then
+			cwd=""
+		fi
+
+		case $com in
+			create* |cr*)
+				createShelter $com
 				;;
-			-h|--help)
+			rm*|del* )
+				delete $com
+				;;
+			add*|ad*)
+				addPasswords $com
+				;;
+
+			l|list|ls)
+				list_shelters $@
+				;;
+
+			exit|q)
+				exit 0
+				;;
+			
+			-h|--help|?)
 				helpMsg
-				;;
+			;;
 			*)
-				list_shelters $1
+				list_shelters $com
 				;;
-
 		esac
-		exit 0
-
-	else
-		while [[ 1 ]]; do
-
-			read  -e -p "shelter>" -i "$cwd" com
-
-			if [[ $com == "" ]];then
-				cwd=""
-			fi
-
-			case $com in
-				l|list|ls)
-					list_shelters $@
-					;;
-
-				exit|q)
-					exit 0
-					;;
-
-				 create)
-					createShelter $com
-					;;
-				rm|del )
-					delete $com
-					;;
-				add )
-					addPasswords $com
-					;;
-				keys)
-					show_keys
-					;;
-				keys | add)
-					add_key
-					;;
-				-h|--help|?)
-					helpMsg
-				;;
-				*)
-					list_shelters $com
-					;;
-			esac
-				
-		done
-	fi
+			
+	done
+fi
 
