file not found repaired

diff --git a/bashShelter b/bashShelter
--- a/bashShelter
+++ b/bashShelter
@@ -1,7 +1,7 @@
 #! /bin/bash 
 # config="$HOME/.config/shelter/"
 # encryptedFile="$HOME/.config/shelter_p"
-encryptedFileName="shelter.tar.gpg"
+encryptedFileName="Ashelter.tar.gpg"
 encryptedFileLocation="/media/veracrypt1"
 encryptedFile="$encryptedFileLocation/$encryptedFileName"
 
@@ -13,7 +13,7 @@ configFileName="shelter"
 config="$configDir/$configFileName"
 
 trap appExit EXIT
-trap appExit ERR
+
 
 
 function helpMsg(){
@@ -29,7 +29,12 @@ function helpMsg(){
 }
  
 function appExit {
-	tree2=`ls -R $config`
+	tree2=`ls -R $config 2>/dev/null`
+
+	if ! [[ -a $encryptedFile ]]; then
+		echo exiting
+	
+	fi
 
 	if [[ $tree1 != $tree2 ]]; then
 		res=""
@@ -39,97 +44,58 @@ function appExit {
 		if [[ $res == "N" || $res == "n" ]]; then
 			echo "aborting"
 		else
-			{
-				cp $encryptedFile "$encryptedFileLocation/.$encryptedFileName""_0"
-				# err=`gpgtar -C $configDir -c --output $encryptedFile $configFileName  > /dev/null` 
-				echo "gpgtar -C $configDir -c --output $encryptedFile $configFileName"
-			
-				for (( i = 1; i <= 6; i++ )); do
-					if [[ $i == 6 ]]; then
-						setBackup
-						break
-					fi	
-					
-					echo "$i/5 attempt"
-					if [[ $i == 5 ]]; then
-						echo "last attempt!!"
-					fi
-					
-					#try
-					{
-						err=`gpgtar -C $configDir -c --output $encryptedFile $configFileName  2>&1`
-						if ! [[ $err ]];then
-							break;
-						fi
-					#except
-					}||{
-						echo "failed"
-						
-
-					}
-				done
-				echo "gpgtar succeed"
-				rm	"$encryptedFileLocation/.$encryptedFileName""_0"
-
-				
-			}||{
-				echo "password input failed, try again."
-				echo "saving error"
-			}
-
+			saveFile
 		fi
 
-
 	fi
-	rm -r $config
+	rm -r $config 1>&2 2>/dev/null
 	exit 0
+}
+
+function saveFile {
+	{
+		cp $encryptedFile "$encryptedFileLocation/.$encryptedFileName""_0"
+		# err=`gpgtar -C $configDir -c --output $encryptedFile $configFileName  > /dev/null` 
+		echo "gpgtar -C $configDir -c --output $encryptedFile $configFileName"
+	
+		for (( i = 1; i <= 6; i++ )); do
+			if [[ $i == 6 ]]; then
+				setBackup
+				break
+			fi	
+			
+			echo "$i/5 attempt"
+			if [[ $i == 5 ]]; then
+				echo "last attempt!!"
+			fi
+			
+			#try
+			{
+				err=`gpgtar -C $configDir -c --output $encryptedFile $configFileName  2>&1`
+				if ! [[ $err ]];then
+					break;
+				fi
+			#except
+			}||{
+				echo "failed"
+				
+
+			}
+		done
+		echo "gpgtar succeed"
+		rm	"$encryptedFileLocation/.$encryptedFileName""_0"
+
+		
+	}||{
+		echo "password input failed, try again."
+		echo "saving error"
+	}
 }
 
 function setBackup {
 	echo setBackup
 	mv "$encryptedFileLocation/.$encryptedFileName""_0" $encryptedFile
 }
-
-# function appExitBACK {
-# 	tree2=`ls -R $config`
-
-# 	if [[ $tree1 != $tree2 ]]; then
-# 		res=""
-
-# 		read  -e -p "want to save? y/N:  " res
-
-# 		if [[ $res == "N" || $res == "n" ]]; then
-# 			echo "aborting"
-# 			rm -r $config
-
-# 		else
-# 			{
-# 				while [[ 1 ]]; do
-# 				cp $encryptedFile "$encryptedFileLocation/.$encryptedFileName""_0"
-# 				# err=`gpgtar -C $configDir -c --output $encryptedFile $configFileName  > /dev/null` 
-				
-# 				if [[ `gpgtar -C $configDir -c --output $encryptedFile $configFileName  ` ]]; then
-# 					exit "gpgtar succeed"
-# 				else
-# 					echo failed
-# 					echo $err
-# 					# mv "$encryptedFileLocation/.$encryptedFileName""_0" $encryptedFile
-					
-# 				fi
-# 				echo "password input failed, try again."
-# 				done				
-# 			}||{
-# 				echo "saving error"
-# 			}
-# 			rm -r $config
-# 		fi
-# 	else
-# 			rm -r $config
-# 	fi
-
-# 	exit 0
-# }
-
 
 
 function clipboard(){
@@ -191,13 +157,13 @@ function list_shelters(){
 			fi
 
 			tmplist=`ls -w 1 $config/$arg1 2>/dev/null`
-	}||{
 	# exccept
+	}||{
 		{
 		#try
 			tmplist=`ls -w 1 $config/$arg1* 2>/dev/null`
-		}||{
 		#except
+		}||{
 			tmplist=`ls -w 1 $config 2>/dev/null`
 			echo '<---- '$arg1' not found ---->'
 			show=1
@@ -216,6 +182,8 @@ function list_shelters(){
 		no_argv
 
 	fi
+
+	echo $tmplist
 	
 	arg1=$cwd$arg1
 
@@ -234,8 +202,6 @@ function createShelter(){
 
 	unset $array
 	list_shelters
-
-
 
 }
 
@@ -266,12 +232,14 @@ function delete(){
 		done
 }
 
-if [[ `gpgtar -C $configDir --decrypt $encryptedFile 2>&1 2>/dev/null` ]]; then
-	echo success
-else
-	echo error
 
+if ![[ -a $encryptedFile ]]; then
+	echo "encrypted file not found"
+	exit 0
 fi
+
+gpgtar -C $configDir --decrypt $encryptedFile 2>&1 2>/dev/null
+
 tree1=`ls -R $config`
 
 cwd=""
